package portugues.phrasesets;

import flow.IProjectVariables;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 20 DE FEVEREIRO DE 2023 16H33MIN30S BRT
 */
public class custom extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(24);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: 011
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "011", "011.wav", "Seja Bem vindo ao nosso centro de atendimento"); 

		// phrase: 004
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "004", "004.wav", "para pessoa fisica tecle 1, para pessoa juridica tecle 2"); 

		// phrase: 005
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "005", "005.wav", "digite seu CPF"); 

		// phrase: 009
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "009", "009.wav", "zelamos pela sua segurança,  Por isso a partir de esse momento, sua ligação podera ser gravada,  Aguarde para ser atendido"); 

		// phrase: 006
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "006", "006.wav", "Dados inválidos"); 

		// phrase: 010
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "010", "010.wav", "Não foi possivel confirmar seus dados., Agradecemos sua ligação, Estamos 24 horas trabalhando para melhor atendelo, Ligue novamente mais tarde"); 

		// phrase: 007
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "007", "007.wav", "Digite seu CNPJ"); 

		// phrase: 008
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "008", "008.wav", "esta e uma opção invalida, tente novamente"); 

		// phrase: 012
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "012", "012.wav", "Estamos com problemas no atendimento, ligue novamente mais tarde."); 

		// phrase: 013
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "013", "013.wav", "Olá , Feliz Páscoa"); 

		// phrase: 014
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "014", "014.wav", "Olá, feliz natal e um prospero ano novo"); 

		// phrase: 015
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "015", "015.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 21 DE MARÇO DE 2023 18H51MIN11S BRT
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
	    String nomeCliente = getMySession().getVariable(IProjectVariables.VALOR_NOME).getSimpleVariable().getStringValue();
	    if (phraseName.equalsIgnoreCase("015") && nomeCliente != null) {
	        com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "015", "015.wav", nomeCliente);
	    }
	    return getPhrase(PHRASE_MAP, phraseName);
	}
	/*public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
	    String nomeCliente = getMySession().getVariable(IProjectVariables.VALOR_NOME).getSimpleVariable().getStringValue();
	    if (phraseName.equalsIgnoreCase("015") && nomeCliente != null) {
	        com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "015", "015.wav", nomeCliente);
	    }
	    return getPhrase(PHRASE_MAP, phraseName);
	}*/
}
