package portugues.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 20 DE FEVEREIRO DE 2023 16H25MIN26S BRT
 */
public class untitled extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(8);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: 001
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "001", "001.wav", "bom dia"); 

		// phrase: 002
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "002", "02.wav", "boa tarde"); 

		// phrase: 003
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "003", "003.wav", "boa noite"); 

		// phrase: 000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "000", "000.wav", "Oi"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 20 DE MARÇO DE 2023 14H58MIN4S BRT
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(untitled.PHRASE_MAP, phraseName));
	}
}
