/**
 * Last generated by Orchestration Designer at: 25 DE FEVEREIRO DE 2023 12H52MIN56S BRT
 */
package portugues.prompts;

public class an_custom extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for an_custom.
	 */
	public an_custom() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 20 DE MARÇO DE 2023 14H58MIN4S BRT
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("an_custom");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

		if ( new com.avaya.sce.runtime.Condition( "condition", "audio", com.avaya.sce.runtime.Expression.STRING_EQUAL, "12", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"custom:012",false));
		}

		if ( new com.avaya.sce.runtime.Condition( "condition", "audio", com.avaya.sce.runtime.Expression.STRING_EQUAL, "13", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"custom:013",false));
		}

		if ( new com.avaya.sce.runtime.Condition( "condition", "audio", com.avaya.sce.runtime.Expression.STRING_EQUAL, "14", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"custom:014",false));
		}

	}
}
