<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="" descriptorversion="1.0" entrypoint="ConsultaPessoaGV/Start" forcesubdialogcall="false" frameworkversion="07.22.10.04" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="" submitmethod="get" version="1.0.0" webname="ConsultaPessoaGV">
    <description/>
    <output defaultvalue="&quot;&quot;" description="" name="Nome" varreftypesimple="true"/>
    <language name="portugues" root="pt-br"/>
    <dependencies/>
</module>
